name: Publish as Container Image

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: latest
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          latest=$(gh release view --repo MCCTeam/Minecraft-Console-Client --json tagName -q .tagName)
          echo "tag=$latest" >> "$GITHUB_OUTPUT"

      - name: Compare with last known release
        id: compare
        run: |
          state_file="release-mark.txt"
          old_tag=""

          if [ -f "$state_file" ]; then
            old_tag=$(cat "$state_file")
          fi

          new_tag="${{ steps.latest.outputs.tag }}"

          echo "old=$old_tag"
          echo "new=$new_tag"

          if [ "$old_tag" != "$new_tag" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.compare.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'

      - name: Log in to GHCR
        uses: docker/login-action@v2
        if: steps.compare.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to ACR
        uses: docker/login-action@v2
        if: steps.compare.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - uses: actions/setup-dotnet@v6
        if: steps.compare.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        with:
          dotnet-version: '10.0'

      - name: Clone
        if: steps.compare.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          git clone https://github.com/MCCTeam/Minecraft-Console-Client -b ${{ steps.latest.outputs.tag }} --recursive Minecraft-Console-Client;

      - name: Build
        if: steps.compare.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          dotnet build -o ./app/linux/amd64  -r linux-x64 -p:PublichReadyToRun=true -c Release Minecraft-Console-Client/MinecraftClient/MinecraftClient.csproj
          dotnet build -o ./app/linux/arm64  -r linux-arm64 -p:PublichReadyToRun=true -c Release Minecraft-Console-Client/MinecraftClient/MinecraftClient.csproj

      - name: Build docker and push to GHCR
        uses: docker/build-push-action@v7
        if: steps.compare.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64/v8
          sbom: false
          provenance: mode=min
          tags: |
            ghcr.io/${{ github.repository_owner }}/minecraft-console-client-docker:latest
            ghcr.io/${{ github.repository_owner }}/minecraft-console-client-docker:${{ steps.latest.outputs.tag }}
            ${{ secrets.ACR_REGISTRY_TAG }}:latest
            ${{ secrets.ACR_REGISTRY_TAG }}:${{ steps.latest.outputs.tag }}


      - name: Save latest release tag
        if: steps.compare.outputs.changed == 'true'
        run: |
          mkdir -p .github
          echo "${{ steps.latest.outputs.tag }}" > release-mark.txt

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add release-mark.txt
          git commit -m "Update external release tag to ${{ steps.latest.outputs.tag }}" || exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.compare.outputs.changed == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
